"""Probabilistic file classification."""

from __future__ import annotations

import fnmatch
from pathlib import Path

from harpy.models import ChangedFile, FileCategory

LOCKFILES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "uv.lock",
    "Cargo.lock",
    "Gemfile.lock",
    "composer.lock",
}

GENERATED_GLOBS = (
    "**/generated/**",
    "**/gen/**",
    "**/*.generated.*",
    "**/*_pb2.py",
    "**/*.g.cs",
    "**/openapi-client/**",
    "**/vendor/**",
)

GENERATED_HEADERS = ("do not edit", "generated by", "auto-generated", "autogenerated")

TEST_GLOBS = (
    "**/tests/**",
    "**/test/**",
    "**/test_*.py",
    "**/*_test.py",
    "**/*.spec.ts",
    "**/*.test.ts",
)
MIGRATION_GLOBS = ("**/migrations/**", "**/alembic/**", "**/db/migrate/**")
AUTH_GLOBS = ("**/auth/**", "**/*permission*", "**/*rbac*")
API_GLOBS = ("**/api/**", "**/controllers/**", "**/routes/**", "**/*_controller.*")
DATA_GLOBS = ("**/models/**", "**/db/**", "**/repositories/**")
CONFIG_GLOBS = ("**/*.toml", "**/*.yaml", "**/*.yml", "**/*.ini", "**/.env*")
UI_GLOBS = ("**/*.tsx", "**/*.jsx", "**/components/**", "**/frontend/**")
DOC_GLOBS = ("**/*.md", "**/docs/**")
BUILD_GLOBS = ("**/Makefile", "**/*.mk", "**/Dockerfile", "**/package.json")
CI_GLOBS = ("**/.github/**", "**/.gitlab-ci.yml", "**/Jenkinsfile")
SNAPSHOT_GLOBS = ("**/*.snap", "**/__snapshots__/**")


def _match(path: str, globs: tuple[str, ...]) -> bool:
    normalized = path.replace("\\", "/")
    name = Path(normalized).name
    return any(
        fnmatch.fnmatch(normalized, pattern) or fnmatch.fnmatch(name, pattern) for pattern in globs
    )


def _header_generated(header: str) -> bool:
    lower = header.lower()
    return any(token in lower for token in GENERATED_HEADERS)


def classify_path(
    path: str, *, header: str = "", extra_generated: tuple[str, ...] = ()
) -> dict[str, float]:
    scores = {category.value: 0.0 for category in FileCategory}
    name = Path(path).name
    if name in LOCKFILES:
        scores[FileCategory.LOCKFILE] = 1.0
    if _match(path, GENERATED_GLOBS + extra_generated) or _header_generated(header):
        scores[FileCategory.GENERATED] = max(
            scores[FileCategory.GENERATED], 0.95 if _header_generated(header) else 0.85
        )
    if _match(path, TEST_GLOBS):
        scores[FileCategory.TEST] = 0.9
    if _match(path, MIGRATION_GLOBS):
        scores[FileCategory.MIGRATION] = 0.9
    if _match(path, AUTH_GLOBS):
        scores[FileCategory.AUTH] = 0.8
    if _match(path, API_GLOBS):
        scores[FileCategory.API] = 0.75
    if _match(path, DATA_GLOBS):
        scores[FileCategory.DATA] = 0.7
    if _match(path, CONFIG_GLOBS):
        scores[FileCategory.CONFIG] = 0.7
    if _match(path, UI_GLOBS):
        scores[FileCategory.UI] = 0.65
    if _match(path, DOC_GLOBS):
        scores[FileCategory.DOCUMENTATION] = 0.85
    if _match(path, BUILD_GLOBS):
        scores[FileCategory.BUILD] = 0.6
    if _match(path, CI_GLOBS):
        scores[FileCategory.CI] = 0.85
    if _match(path, SNAPSHOT_GLOBS):
        scores[FileCategory.SNAPSHOT] = 0.9
    if max(scores.values()) < 0.4 and path.endswith((".py", ".ts", ".go", ".rs", ".java")):
        scores[FileCategory.BUSINESS_LOGIC] = 0.55
    if max(scores.values()) == 0.0:
        scores[FileCategory.UNKNOWN] = 1.0
    return scores


def apply_classification(
    file: ChangedFile, *, header: str = "", extra_generated: tuple[str, ...] = ()
) -> ChangedFile:
    scores = classify_path(file.path, header=header, extra_generated=extra_generated)
    file.category_scores = scores
    file.generated_probability = scores.get(FileCategory.GENERATED, 0.0)
    file.test_probability = scores.get(FileCategory.TEST, 0.0)
    file.business_logic_probability = scores.get(FileCategory.BUSINESS_LOGIC, 0.0)
    return file


def primary_category(scores: dict[str, float]) -> FileCategory:
    if not scores:
        return FileCategory.UNKNOWN
    best = max(scores, key=lambda key: scores[key])
    return FileCategory(best)
